.TH sfi 1 sfi\-VERSION
.SH NAME
sfi \- simple file importer
.SH SYNOPSIS
.B sfi
.RB [ \-h ]
.RB [ \-v ]
.RB [ file ]
.SH DESCRIPTION
sfi is able to import 
files in files and print them as a unique template.
.SH OPTIONS
.TP
.B \-v
prints version information to standard output, then exits.
.TP
.B \-h
prints usage information to standard output, then exits.
.SH BUGS
Please report any Bugs to https://github.com/bomboclat/sfi/issues or via mail.
